alias ll='ls -alh'
#export PATH=/usr/local/bin:/usr/local/sbin:/Users/awatkins/bin:$PATH
export PATH="/usr/local/opt/python/libexec/bin:~/bin:$PATH"
alias newpass='openssl rand -base64 12'
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
export PATH="/usr/local/sbin:$PATH"
export HISTFILESIZE=200000
